package game;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class DataAccess {
	private FileReader fileReader;
	private FileWriter fileWriter;
	private String FilePath;

	private BufferedReader bufferedReader;
	private BufferedWriter bufferedWriter;
	
	private String[] Profiles = new String[3];

	public DataAccess() {

		// Used to open a new Data Storing File to that will be used to Store Program
		// Data

		FilePath = "data/ProgramData.txt";
		boolean Writer = true;

		// Defines fileReader
		try {
			// Locates Previously Declared Data Storing File
			fileReader = new FileReader(FilePath);
		} catch (FileNotFoundException ex1) {
			// Creates New Data Storing File
			try {
				File file = new File(FilePath);
				try {
					file.createNewFile();
				} catch (IOException ex3) {
					ex3.printStackTrace();
				}
				fileReader = new FileReader(FilePath);

				// Formats
				Writer = false;
				try {
					// Locates Previously Declared Data Storing File
					fileWriter = new FileWriter(FilePath);
				} catch (IOException ex4) {
					ex4.printStackTrace();
				}
				
				bufferedWriter = new BufferedWriter(fileWriter);
				try {
				bufferedWriter.write("DO NOT EDIT THIS FILE, AS DOING SO WILL CORRUPT THE PROGRAM DATA!!! -Team BadFish");
				bufferedWriter.newLine();
				bufferedWriter.newLine();
				bufferedWriter.write("Player Profiles:");
				bufferedWriter.newLine();
				bufferedWriter.close();
				} catch(IOException ex5) {
					ex5.printStackTrace();
				}

			} catch (FileNotFoundException ex2) {
				ex2.printStackTrace();
			}
		}

		// Defines fileWriter
		if (Writer) {
			try {
				// Locates Previously Declared Data Storing File
				fileWriter = new FileWriter(FilePath);
			} catch (IOException ex1) {
				ex1.printStackTrace();
			}
		}
		
		

	}

}
